Merge 'deploy' branch.
Squashed commit of the following:

commit 6e84878dd7fa45a3dcd6d35be2b517e994cfb379
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 26 16:21:19 2017 -0400

    actually, only deploy on tags after all

commit 05613ee7a8bdc0c562c86bb32b2ace22276797f6
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 26 15:57:07 2017 -0400

    travis: remove old deployment config

commit 1e82daa13540259d346297f72fa77258c33f22e4
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 26 15:52:16 2017 -0400

    travis: remove deploy.tags = true -- it limits deploys to *only* tagged commits

commit 10eba439dd2c61e84c5e6794bbc48218c0ca8e6d
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 26 15:36:36 2017 -0400

    after uploading a release, link it as latest.img.gz

commit 0062455d2e5be272ffb62c9efeb344a484cc3b10
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 26 15:36:22 2017 -0400

    deploy on all branches, and on tags

commit 923755d4482295de30bc31b171cca07ea9e04557
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 26 15:32:29 2017 -0400

    upload directly to images directory

commit 928be767a46de05f5d089a57127335062b151d5c
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 26 15:31:09 2017 -0400

    name uploaded images after release tag or branch + revision

commit 5566dfce95c0a03f6d5d5b733817c4ffadd6bb21
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 19 18:05:36 2017 -0400

    deploy: create images/ before running t-b

    This way, the directory is not owned by root, and the build user can create new files in it.

commit a491a8cd162fe69376041c9f40b16418f0beed8e
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 19 17:03:54 2017 -0400

    deploy: use gzip stdio instead of missing --keep option

commit 47b6da0011c72b0bc24b8c67daa0caf1f601b632
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 19 17:03:43 2017 -0400

    deploy.sh: set -e

commit 57470bd5f07998dd4d311d0e7ed10c1843d7b6c1
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 19 16:46:44 2017 -0400

    try different permutation of gzip options

commit 9d59cc6d974a6230be50d14d6ef6dda5c2177a4d
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 19 15:42:33 2017 -0400

    deploy: ssh key needs to have restrictive permissions

commit a85557d3c7a05c31bda5937ff19fad9c6f8cfb1a
Author: Dafydd Harries <daf@rhydd.org>
Date:   Tue Jul 18 11:23:46 2017 -0400

    deploy: make known_hosts a "global" rather than "user" file

    This means that ssh doesn't modify the file, which we don't want.

commit ddbdc82d3f4c7ef32783c090a91c6a53beb07773
Author: Dafydd Harries <daf@rhydd.org>
Date:   Tue Jul 18 11:21:40 2017 -0400

    deploy: check that we found an image

commit 88705eed3117668c86b67523ffdc50f7dbf40a11
Author: Dafydd Harries <daf@rhydd.org>
Date:   Tue Jul 18 11:21:12 2017 -0400

    deploy: set -x to help debugging

commit d462fd2430a5bb0f350bfc73c2f5aade2c488efc
Author: Dafydd Harries <daf@rhydd.org>
Date:   Tue Jul 18 11:20:41 2017 -0400

    deploy: only gzip if necessary; keep uncompressed image

commit 5ac65f9b5729dfe3790e63c698396287ca2dbe55
Author: Dafydd Harries <daf@rhydd.org>
Date:   Tue Jul 18 09:27:41 2017 -0400

    deploy: variable assignment needs to be quoted

commit 123dea6d5723b52531d6e9f55aae9e89ea4f5722
Author: Dafydd Harries <daf@rhydd.org>
Date:   Tue Jul 18 08:45:51 2017 -0400

    deployment: add known_hosts file to prevent ssh prompt

commit e05801e6e16e4ac68a5e7d11239e21269ff9029b
Author: Dafydd Harries <daf@rhydd.org>
Date:   Mon Jul 17 09:43:26 2017 -0400

    for testing purposes, also deploy from the deploy branch

commit 236f38b0fc775a4cf7bb1e3e55545c664539422b
Author: Dafydd Harries <daf@rhydd.org>
Date:   Sun Jul 16 17:16:31 2017 -0400

    travis: deploy via ssh

commit 77373cf5fd0e0384190b0b05426520299599f05a
Author: Dafydd Harries <daf@rhydd.org>
Date:   Wed Jul 19 16:20:56 2017 -0400

    wip: download via torrent

diff --git a/treehouse-builder b/treehouse-builder
--- a/treehouse-builder
+++ b/treehouse-builder
@@ -14,7 +14,7 @@
 # ADD_REPO_KEYS=()
 
 # Raspbian
-RASPBIAN_URL=http://downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/2017-07-05-raspbian-jessie.zip
+RASPBIAN_TORRENT_URL=http://downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/2017-07-05-raspbian-jessie.zip.torrent
 RASPBIAN_SHA1=e1edd4d26090b3e67a66939fa77eeb656de8a2c5
 
 ############ End of User Cusomization
@@ -43,9 +43,10 @@ function _umount {
 }
 
 function _get_image {
-    echo "Fetching $RASPBIAN_URL "
+    echo "Fetching $RASPBIAN_TORRENT_URL"
     mkdir -p images
-    wget --continue --progress=dot:giga --directory-prefix images $RASPBIAN_URL || die "Download of $RASPBIAN_URL failed"
+    wget "$RASPBIAN_TORRENT_URL" -O "$RASPBIAN_TORRENT" || die "Download of $RASPBIAN_TORRENT failed"
+    aria2c $RASPBIAN_TORRENT -d images --seed-time 0
     echo -n "Checksum of "
     sha1sum --strict --check - <<<"$RASPBIAN_SHA1 *$IMAGE_ZIP" || die "Download checksum validation failed, please check http://www.raspberrypi.org/downloads"
     unzip $IMAGE_ZIP -d images || die "Could not unzip $IMAGE_ZIP"
@@ -178,8 +179,12 @@ function exittrap {
 trap exittrap 0
 trap exittrap ERR
 
-IMAGE_ZIP=images/${RASPBIAN_URL##*/}
+RASPBIAN_TORRENT=images/$(basename $RASPBIAN_TORRENT_URL)
+echo $RASPBIAN_TORRENT
+IMAGE_ZIP=${RASPBIAN_TORRENT%.torrent}
+echo $IMAGE_ZIP
 IMAGE=${IMAGE_ZIP%.zip}.img
+echo $IMAGE
 
 if [ ! -e "$IMAGE" ]; then
     _get_image
