include GPG keys in repository
This makes it easier to run builds without network access.

diff --git a/treehouse-builder b/treehouse-builder
--- a/treehouse-builder
+++ b/treehouse-builder
@@ -182,11 +182,21 @@ function _modify_image {
         done > mnt/img_root/etc/apt/sources.list.d/pirateship-image-creator.list || die "Could not add repos ${ADD_REPOS[@]}"
     fi
     if [[ ${ADD_REPO_KEYS:-} ]] ; then
-        GPG="gpg --no-permission-warning --no-default-keyring --keyring "
-        KEYRING=$PWD/apt_keys.gpg
-        if [[ ! -e $KEYRING ]]; then
-            $GPG $KEYRING --recv-keys ${ADD_REPO_KEYS[@]} || die "Could not download GPG keys ${ADD_REPO_KEYS[@]}"
+        GPG="gpg --no-permission-warning --no-default-keyring --quiet --keyring "
+        KEYRING=$PWD/temp/apt_keys.gpg
+        cat keys/*.key | $GPG $KEYRING --import
+
+        missing_keys=()
+        for key in "${ADD_REPO_KEYS[@]}" ; do
+            if ! $GPG $KEYRING --list-keys $key >/dev/null 2>&1 ; then
+                missing_keys+=( $key )
+            fi
+        done
+
+        if [[ ${#missing_keys[@]} > 0 ]]; then
+            die "missing GPG keys! try: $GPG $KEYRING --recv-keys ${missing_keys[@]}"
         fi
+
         $GPG $KEYRING --export ${ADD_REPO_KEYS[@]} | $GPG mnt/img_root/etc/apt/trusted.gpg --trustdb-name mnt/img_root/etc/apt/trustdb.gpg --import - || die "Could not import GPG keys ${ADD_REPO_KEYS[@]} for apt"
     fi
     if [[ "$SETUP_SSHKEYS" == true ]] ; then
