pass --recv-keys instead of --receive-keys to gpg for compatibility

diff --git a/treehouse-builder b/treehouse-builder
--- a/treehouse-builder
+++ b/treehouse-builder
@@ -184,7 +184,7 @@ function _modify_image {
         GPG="gpg --no-permission-warning --no-default-keyring --keyring "
         KEYRING=$PWD/apt_keys.gpg
         if [[ ! -e $KEYRING ]]; then
-            $GPG $KEYRING --receive-keys ${ADD_REPO_KEYS[@]} || die "Could not download GPG keys ${ADD_REPO_KEYS[@]}"
+            $GPG $KEYRING --recv-keys ${ADD_REPO_KEYS[@]} || die "Could not download GPG keys ${ADD_REPO_KEYS[@]}"
         fi
         $GPG $KEYRING --export ${ADD_REPO_KEYS[@]} | $GPG mnt/img_root/etc/apt/trusted.gpg --trustdb-name mnt/img_root/etc/apt/trustdb.gpg --import - || die "Could not import GPG keys ${ADD_REPO_KEYS[@]} for apt"
     fi
