yolo

diff --git a/treehouse-builder b/treehouse-builder
--- a/treehouse-builder
+++ b/treehouse-builder
@@ -38,6 +38,7 @@ INSTALL_PACKAGES=(
 #    resolvconf #for https://www.npmjs.com/package/pirate-sh
 #    libdbus-1-dev libdbus-glib-1-dev libglib2.0-dev libical-dev libreadline-dev libudev-dev libusb-dev #install ble
 #    make #http://www.elinux.org/RPi_Bluetooth_LE
+     aria2
 )
 
 # List of packages to remove
@@ -79,14 +80,14 @@ function die {
 }
 
 missing_deps=()
-for prog in kpartx wget gpg parted qemu-arm-static ; do
+for prog in kpartx aria2c wget gpg parted qemu-arm-static ; do
     if ! type $prog &>/dev/null ; then
         missing_deps+=( $prog )
     fi
 done
 if (( ${#missing_deps[@]} > 0 )) ; then
     die "Missing required programs: ${missing_deps[*]}
-    On Debian/Ubuntu try 'sudo apt-get install kpartx qemu-user-static parted'"
+    On Debian/Ubuntu try 'sudo apt-get install kpartx qemu-user-static parted aria2'"
 fi
 
 # Constants
@@ -124,7 +125,9 @@ function _get_image {
     echo "Fetching $RASPBIAN_URL "
     mkdir -p images
     RASPBIAN_ARCHIVE_FILE=images/${RASPBIAN_URL##*/}
-    wget --continue --progress=dot:giga --directory-prefix images $RASPBIAN_URL || die "Download of $RASPBIAN_URL failed"
+    # wget --continue --progress=dot:giga --directory-prefix images $RASPBIAN_URL || die "Download of $RASPBIAN_URL failed"
+    wget https://downloads.raspberrypi.org/raspbian_latest.torrent --directory-prefix images
+    aria2c images/raspbian_latest.torrent -d images
     echo -n "Checksum of "
     sha1sum --strict --check - <<<"$RASPBIAN_SHA1 *$RASPBIAN_ARCHIVE_FILE" || die "Download checksum validation failed, please check http://www.raspberrypi.org/downloads"
     unzip $RASPBIAN_ARCHIVE_FILE -d images || die "Could not unzip $RASPBIAN_ARCHIVE_FILE"
