update treehouse-builder.sh (#180)

diff --git a/treehouse-builder b/treehouse-builder
--- a/treehouse-builder
+++ b/treehouse-builder
@@ -30,7 +30,7 @@ source lib.sh
 missing_deps=()
 for prog in kpartx wget gpg parted qemu-arm-static aria2c jq curl; do
     if ! type $prog &>/dev/null ; then
-        missing_deps+=( $prog )
+        missing_deps+=( "$prog" )
     fi
 done
 if (( ${#missing_deps[@]} > 0 )) ; then
@@ -43,6 +43,7 @@ function _umount {
     for dir in "$@" ; do
         if grep -q "$dir" /proc/self/mounts ; then
             if ! umount -f "$dir" ; then
+                # shellcheck disable=SC2046,SC2086
                 die "Could not umount $dir, check running procs:$NL$(lsof 2>/dev/null | grep $(readlink -f $dir))"
             fi
         fi
@@ -52,16 +53,16 @@ function _umount {
 function _get_image {
     echo "Fetching $RASPBIAN_TORRENT_URL"
     mkdir -p images
-    if [ ! -f $RASPBIAN_TORRENT ]; then
+    if [ ! -f "$RASPBIAN_TORRENT" ]; then
       wget "$RASPBIAN_TORRENT_URL" -O "$RASPBIAN_TORRENT" || die "Download of $RASPBIAN_TORRENT failed"
     fi
-    aria2c --continue $RASPBIAN_TORRENT -d images --seed-time 0
+    aria2c --continue "$RASPBIAN_TORRENT" -d images --seed-time 0
     echo -n "Checksum of "
     sha1sum --strict --check - <<<"$RASPBIAN_SHA1 *$IMAGE_ZIP" || die "Download checksum validation failed, please check http://www.raspberrypi.org/downloads"
 }
 
 function _decompress_image {
-    unzip -o $IMAGE_ZIP -d images || die "Could not unzip $IMAGE_ZIP"
+    unzip -o "$IMAGE_ZIP" -d images || die "Could not unzip $IMAGE_ZIP"
 }
 
 function _disable_daemons {
@@ -97,13 +98,13 @@ function _resize_image {
     RESIZE_IMAGE_PATH=images/$RASPBIAN_IMAGE_FILE
     if [[ -L "images" ]];
     then
-        rsync -Pav images/$RASPBIAN_IMAGE_FILE .
+        rsync -Pav "images/$RASPBIAN_IMAGE_FILE" .
         RESIZE_IMAGE_PATH=$RASPBIAN_IMAGE_FILE
     fi
 
-    start_sector=$(fdisk -l $RESIZE_IMAGE_PATH | awk -F" "  '{ print $2 }' | sed '/^$/d' | sed -e '$!d')
-    truncate -s +600M $RESIZE_IMAGE_PATH
-    losetup /dev/loop1 $RESIZE_IMAGE_PATH
+    start_sector=$(fdisk -l "$RESIZE_IMAGE_PATH" | awk -F" "  '{ print $2 }' | sed '/^$/d' | sed -e '$!d')
+    truncate -s +600M "$RESIZE_IMAGE_PATH"
+    losetup /dev/loop1 "$RESIZE_IMAGE_PATH"
     fdisk /dev/loop1 <<EOF
 p
 d
@@ -117,28 +118,30 @@ p
 w
 EOF
     losetup -d /dev/loop1
-    losetup -o $((start_sector*512)) /dev/loop2 $RESIZE_IMAGE_PATH
+    losetup -o $((start_sector*512)) /dev/loop2 "$RESIZE_IMAGE_PATH"
     e2fsck -f /dev/loop2
     resize2fs -f /dev/loop2
     losetup -d /dev/loop2
     if [[ -L "images" ]];
     then
-        rsync -Pav $RASPBIAN_IMAGE_FILE images/
-        rm $RASPBIAN_IMAGE_FILE
+        rsync -Pav "$RASPBIAN_IMAGE_FILE" images/
+        rm "$RASPBIAN_IMAGE_FILE"
     fi
 }
 
 function _open_image {
-    echo "Loop-back mounting" images/$RASPBIAN_IMAGE_FILE
+    echo "Loop-back mounting" "images/$RASPBIAN_IMAGE_FILE"
+    # shellcheck disable=SC2086
     kpartx="$(kpartx -sav images/$RASPBIAN_IMAGE_FILE)" || die "Could not setup loop-back access to $RASPBIAN_IMAGE_FILE:$NL$kpartx"
-    read -d '' img_boot_dev img_root_dev <<<$(grep -o 'loop.p.' <<<"$kpartx")
+    # shellcheck disable=SC2162
+    read -d '' img_boot_dev img_root_dev <<<"$(grep -o 'loop.p.' <<<"$kpartx")"
     test "$img_boot_dev" -a "$img_root_dev" || die "Could not extract boot and root loop device from kpartx output:$NL$kpartx"
     img_boot_dev=/dev/mapper/$img_boot_dev
     img_root_dev=/dev/mapper/$img_root_dev
     mkdir -p mnt/img_root
-    mount -t ext4 $img_root_dev mnt/img_root || die "Could not mount $img_root_dev mnt/img_root"
+    mount -t ext4 "$img_root_dev" mnt/img_root || die "Could not mount $img_root_dev mnt/img_root"
     mkdir -p mnt/img_root/boot || die "Could not mkdir mnt/img_root/boot"
-    mount -t vfat $img_boot_dev mnt/img_root/boot || die "Could not mount $img_boot_dev mnt/img_root/boot"
+    mount -t vfat "$img_boot_dev" mnt/img_root/boot || die "Could not mount $img_boot_dev mnt/img_root/boot"
     echo "Raspbian Image Details:"
     df -h mnt/img_root/boot mnt/img_root | sed -e "s#$(pwd)/##"
 }
@@ -148,7 +151,7 @@ function _close_image {
         mnt/img_root/{proc,sys,run,dev/pts} \
         mnt/sd_root/bo?t mnt/img_root/boot \
         mnt/sd_ro?t mnt/img_root
-    kpartx -d images/$RASPBIAN_IMAGE_FILE >/dev/null
+    kpartx -d "images/$RASPBIAN_IMAGE_FILE" >/dev/null
 }
 
 function _prepare_chroot {
@@ -219,7 +222,7 @@ if [[ "$USER" != root && $(id -u) != "0" ]] ; then
     exit 1
 fi
 
-if grep -wq $(readlink -f mnt) /proc/self/mounts; then
+if grep -wq "$(readlink -f mnt)" /proc/self/mounts; then
     die "mnt/ is already mounted!"
 fi
 
@@ -233,11 +236,11 @@ trap exittrap 0
 trap exittrap ERR
 
 RASPBIAN_TORRENT=images/$(basename $RASPBIAN_TORRENT_URL)
-echo $RASPBIAN_TORRENT
+echo "$RASPBIAN_TORRENT"
 IMAGE_ZIP=${RASPBIAN_TORRENT%.torrent}
-echo $IMAGE_ZIP
+echo "$IMAGE_ZIP"
 IMAGE=${IMAGE_ZIP%.zip}.img
-echo $IMAGE
+echo "$IMAGE"
 
 if [ ! -e "$IMAGE_ZIP" ]; then
     _get_image
