get extra GPG keys from keyserver instead of system apt keyring
This makes the script more independent from host system configuration and requires less setup by
users.

diff --git a/treehouse-builder b/treehouse-builder
--- a/treehouse-builder
+++ b/treehouse-builder
@@ -175,7 +175,12 @@ function _modify_image {
         done > mnt/img_root/etc/apt/sources.list.d/pirateship-image-creator.list || die "Could not add repos ${ADD_REPOS[@]}"
     fi
     if [[ ${ADD_REPO_KEYS:-} ]] ; then
-        gpg --no-permission-warning --no-default-keyring --keyring /etc/apt/trusted.gpg --export ${ADD_REPO_KEYS[@]} | gpg --no-permission-warning --no-default-keyring --keyring mnt/img_root/etc/apt/trusted.gpg --trustdb-name mnt/img_root/etc/apt/trustdb.gpg --import - || die "Could not import GPG keys ${ADD_REPO_KEYS[@]} for apt"
+        GPG="gpg --no-permission-warning --no-default-keyring --keyring "
+        KEYRING=apt_keys.gpg
+        if [[ ! -e $KEYRING ]]; then
+            $GPG $KEYRING --receive-keys ${ADD_REPO_KEYS[@]} || die "Could not download GPG keys ${ADD_REPO_KEYS[@]}"
+        fi
+        $GPG $KEYRING --export ${ADD_REPO_KEYS[@]} | $GPG mnt/img_root/etc/apt/trusted.gpg --trustdb-name mnt/img_root/etc/apt/trustdb.gpg --import - || die "Could not import GPG keys ${ADD_REPO_KEYS[@]} for apt"
     fi
     if [[ "$SETUP_SSHKEYS" == true ]] ; then
         IFS=: read a b c d e user_home g < <(getent passwd ${SUDO_USER:-$USER})
