only get image if it isn't already present

diff --git a/treehouse-builder b/treehouse-builder
--- a/treehouse-builder
+++ b/treehouse-builder
@@ -47,11 +47,10 @@ function _umount {
 function _get_image {
     echo "Fetching $RASPBIAN_URL "
     mkdir -p images
-    RASPBIAN_ARCHIVE_FILE=images/${RASPBIAN_URL##*/}
     wget --continue --progress=dot:giga --directory-prefix images $RASPBIAN_URL || die "Download of $RASPBIAN_URL failed"
     echo -n "Checksum of "
-    sha1sum --strict --check - <<<"$RASPBIAN_SHA1 *$RASPBIAN_ARCHIVE_FILE" || die "Download checksum validation failed, please check http://www.raspberrypi.org/downloads"
-    unzip $RASPBIAN_ARCHIVE_FILE -d images || die "Could not unzip $RASPBIAN_ARCHIVE_FILE"
+    sha1sum --strict --check - <<<"$RASPBIAN_SHA1 *$IMAGE_ZIP" || die "Download checksum validation failed, please check http://www.raspberrypi.org/downloads"
+    unzip $IMAGE_ZIP -d images || die "Could not unzip $IMAGE_ZIP"
 }
 
 function _disable_daemons {
@@ -177,8 +176,13 @@ function exittrap {
 trap exittrap 0
 trap exittrap ERR
 
+IMAGE_ZIP=images/${RASPBIAN_URL##*/}
+IMAGE=${IMAGE_ZIP%.zip}.img
 
-_get_image
+if [ ! -e "$IMAGE" ]; then
+    _get_image
+fi
+
 _open_image
 _modify_image
 
